# Generated by Django 2.2.4 on 2020-12-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtm_test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='icon',
            field=models.TextField(default='https://i.imgur.com/5OttL91.jpg'),
            preserve_default=False,
        ),
    ]
